#!/usr/bin/env bash
# PHASE B (optional): UPS through NUT — a clean shutdown when the battery runs out.
#
# Only makes sense if the UPS has a DATA USB port (not just charging).
# Run this once the UPS is already connected to the Pi over USB:
#   sudo ~/shibuya/bootstrap.sh --only 90
set -Eeuo pipefail
source "${SHIBUYA_ROOT:?}/lib/common.sh"
require_root
ensure_dirs

section "looking for a UPS on USB"
apt_install nut-client nut-server usbutils

# nut-scanner probes USB and finds a supported driver on its own.
SCAN="$(nut-scanner -U -q 2>/dev/null || true)"
if [[ -z "$SCAN" ]] || ! contains "$SCAN" 'driver'; then
  warn "No UPS found on USB."
  echo
  echo "  Possible reasons:"
  echo "    - the UPS is only plugged in for power, the data cable is not connected"
  echo "    - the model has no data USB port (a 'dumb' UPS)"
  echo
  warn "Without a link to the UPS the Pi will lose power abruptly when the battery dies."
  warn "For an SD card that is the main way to end up with a corrupted filesystem —"
  warn "one more argument for moving to an SSD soon."
  echo
  echo "  Currently connected over USB:"
  lsusb | sed 's/^/    /'
  exit 0
fi

ok "UPS found:"
printf '%s\n' "$SCAN" | sed 's/^/    /'

section "NUT configuration"
# Standalone: the UPS serves this machine only, no networking involved.
NUT_PASS_FILE="${SHIBUYA_ETC}/nut-upsmon.pass"
if [[ ! -f "$NUT_PASS_FILE" ]]; then
  install -m 0600 -o root -g root /dev/null "$NUT_PASS_FILE"
  head -c 24 /dev/urandom | base64 > "$NUT_PASS_FILE"
fi
NUT_PASS="$(cat "$NUT_PASS_FILE")"
write_file /etc/nut/ups.conf 0640 "root:nut" <<EOF
# shibuya: generated by nut-scanner
maxretry = 3

$(printf '%s\n' "$SCAN")
EOF
if changed; then ok "ups.conf written"; fi

write_file /etc/nut/nut.conf 0640 "root:nut" <<'EOF'
MODE=standalone
EOF

write_file /etc/nut/upsd.users 0640 "root:nut" <<EOF
[upsmon]
    password = ${NUT_PASS}
    upsmon primary
EOF

UPSNAME="$(printf '%s' "$SCAN" | grep -oE '^\[[^]]+\]' | head -1 | tr -d '[]')"
UPSNAME="${UPSNAME:-ups}"

write_file /etc/nut/upsmon.conf 0640 "root:nut" <<EOF
# shibuya: shut down early rather than at full discharge — an abrupt power cut
# on an SD card easily leaves a corrupted filesystem.
MONITOR ${UPSNAME}@localhost 1 upsmon ${NUT_PASS} primary
MINSUPPLIES 1
SHUTDOWNCMD "/sbin/shutdown -h +0"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
POWERDOWNFLAG /etc/killpower
RUN_AS_USER root

# Power lost / restored / battery running out — notify via Telegram.
NOTIFYCMD /usr/local/bin/shibuya-ups-notify
NOTIFYFLAG ONBATT  SYSLOG+EXEC
NOTIFYFLAG ONLINE  SYSLOG+EXEC
NOTIFYFLAG LOWBATT SYSLOG+EXEC
NOTIFYFLAG SHUTDOWN SYSLOG+EXEC
EOF

write_file /usr/local/bin/shibuya-ups-notify 0755 <<'EOF'
#!/usr/bin/env bash
# upsmon calls this script whenever the power state changes.
set -uo pipefail
[[ -f /etc/shibuya/move.env ]] && source /etc/shibuya/move.env
[[ -z "${TELEGRAM_BOT_TOKEN:-}" ]] && exit 0

CHARGE="$(upsc "$(upsc -l 2>/dev/null | head -1)" battery.charge 2>/dev/null || echo '?')"
RUNTIME="$(upsc "$(upsc -l 2>/dev/null | head -1)" battery.runtime 2>/dev/null || echo '?')"
[[ "$RUNTIME" =~ ^[0-9]+$ ]] && RUNTIME="$((RUNTIME / 60)) min"

curl -fsS --max-time 15 \
  -d "chat_id=${TELEGRAM_CHAT_ID}" \
  --data-urlencode "text=shibuya UPS: ${1:-event}
Charge: ${CHARGE}%  Runtime left: ${RUNTIME}" \
  "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" >/dev/null
EOF

chown root:nut /etc/nut/*.conf 2>/dev/null || true
systemctl restart nut-server nut-monitor 2>/dev/null || true
enable_now nut-server.service
enable_now nut-monitor.service

sleep 3
if upsc "${UPSNAME}" >/dev/null 2>&1; then
  ok "UPS is being polled:"
  upsc "${UPSNAME}" 2>/dev/null | grep -E 'battery.charge|battery.runtime|ups.status|ups.model' | sed 's/^/    /'
else
  warn "upsc does not respond — check: journalctl -u nut-server -n 30"
fi

ok "90-ups done"
